In [ ]:
#pip install numpy

In [ ]:
import numpy as np

In [ ]:
p = [1, 4.4, 'Lundi']

In [ ]:
p

In [ ]:
p.append(100)

In [ ]:
Liste =[i**2 for i in range(10)]
Liste

In [ ]:
def f(x):
    return x**3

In [ ]:
[f(x) for x in Liste]

In [1]:
import numpy as np

In [ ]:
tab = np.array([1, 4, 5])
type(tab)

In [ ]:
type(Liste)

In [ ]:
tab1 = np.array([1, 13.6])
tab1

In [ ]:
tab2 = np.array([1, 13.6, 'Lundi'])
tab2

In [ ]:
T = np.array([1, 13])
T

In [ ]:
type(T[0])

In [ ]:
T = np.array([256, 3], dtype=np.uint8)
T

In [ ]:
np.linspace(0,10,5)

In [ ]:
def f(x) :
    return x**3
def g(x):
    return x**2

In [ ]:
import matplotlib.pyplot as plt
X = np.linspace(-10,10,1000)
#plt.plot(X, f(X),'r')
plt.plot(X,g(X),'g')

In [ ]:
x = np.random.random() # [0, 1[

In [ ]:
t = x = np.random.random(3)

In [ ]:
x = np.random.random((3,5))

In [ ]:
t = np.random.randint(-3,3)

In [ ]:
t = np.random.randint(-3,3,2)

In [ ]:
t = np.random.randint(-3,3,(2,3))

In [27]:
etudiants = np.arange(1,21)
np.random.choice(etudiants)

12

In [28]:
tab = np.array([1, 5, 0])
tab

array([1, 5, 0])

In [33]:
M = np.array([[1,3,4,5],[2,5,0,0],[0,1,1, 10]])
M

array([[ 1,  3,  4,  5],
       [ 2,  5,  0,  0],
       [ 0,  1,  1, 10]])

In [32]:
M[0,0], M[1,0]

(1, 2)

In [37]:
M[1:,:2]

array([[2, 5],
       [0, 1]])

In [42]:
M = np.random.random((3,5))
M

array([[0.11188927, 0.88371475, 0.7575798 , 0.53450927, 0.39569861],
       [0.56711514, 0.10659276, 0.35457705, 0.26639736, 0.61561928],
       [0.07914383, 0.27987632, 0.60512045, 0.21835162, 0.45166534]])

In [43]:
M = np.random.randint(1,5,(3,5))
M

array([[4, 2, 1, 3, 3],
       [1, 1, 2, 1, 2],
       [1, 4, 4, 1, 1]])

In [45]:
#M.size
np.size(M)

15

In [47]:
#M.shape
np.shape(M)

(3, 5)

In [48]:
M.reshape(5,3)

array([[4, 2, 1],
       [3, 3, 1],
       [1, 2, 1],
       [2, 1, 4],
       [4, 1, 1]])

In [50]:
M.flatten()

array([4, 2, 1, 3, 3, 1, 1, 2, 1, 2, 1, 4, 4, 1, 1])

In [51]:
M.ravel()

array([4, 2, 1, 3, 3, 1, 1, 2, 1, 2, 1, 4, 4, 1, 1])

In [56]:
A = np.random.randint(1,5,(2,3))
B = np.random.randint(1,5,(3,3))
C = np.random.randint(1,5,(2,2))
A, B, C

(array([[1, 3, 3],
        [3, 1, 2]]),
 array([[2, 4, 2],
        [3, 4, 3],
        [2, 3, 3]]),
 array([[3, 2],
        [2, 1]]))

In [59]:
np.hstack((A,C))

array([[1, 3, 3, 3, 2],
       [3, 1, 2, 2, 1]])

In [60]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 1, 3], [3, 2, 1]])

In [62]:
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2, 1, 3],
        [3, 2, 1]]))

In [64]:
a*b

array([[ 2,  2,  9],
       [12, 10,  6]])

In [66]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[4], [2],[1]])
a.shape, b.shape

((2, 3), (3, 1))

In [67]:
np.dot(a,b)

array([[11],
       [32]])

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
#Créer une image noire de (200x100) pixels
image = np.zeros((200,100), dtype=np.uint8)

In [79]:
import cv2
cv2.imshow("noire",image)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [80]:
from numpy.linalg import det

In [84]:
a = np.array(np.eye(3))
det(a)

1.0

In [85]:
a = np.random.randint(0,10,(3,4))
a

array([[8, 6, 3, 8],
       [7, 3, 3, 6],
       [1, 2, 6, 5]])

In [86]:
a.sum()

58

In [87]:
a.sum(axis=0)

array([16, 11, 12, 19])

In [89]:
notes = np.array([12,18,9,14])
notes[notes<10]

array([9])